# Generated by Django 3.0.6 on 2020-09-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200909_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(default='', max_length=111),
        ),
    ]
