# Generated by Django 3.0.6 on 2020-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderupdate',
            fields=[
                ('updateid', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(default='')),
                ('updatedesc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
